plugins {
    java
    application
    id("com.gradleup.shadow") version "8.3.6"
}

group = "dev.rambris"
version = "0.0.1-beta.4"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "dev.rambris.amigaamos.Main"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    implementation("info.picocli:picocli:4.7.6")
    annotationProcessor("info.picocli:picocli-codegen:4.7.6")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// ---------------------------------------------------------------------------
// Version code generation
// ---------------------------------------------------------------------------

val generateVersion by tasks.registering {
    val versionString = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/version/main/java")
    inputs.property("version", versionString)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.resolve("dev/rambris/amigaamos")
        dir.mkdirs()
        dir.resolve("Version.java").writeText(
            """
            package dev.rambris.amigaamos;

            /** Generated by Gradle — do not edit. Version reflects {@code project.version} in build.gradle.kts. */
            public final class Version {
                public static final String VALUE = "$versionString";
                private Version() {}
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.main {
    java.srcDir(generateVersion.map { layout.buildDirectory.dir("generated/sources/version/main/java").get() })
}

tasks.test {
    useJUnitPlatform()
}
