plugins {
    java
    application
    id("com.gradleup.shadow") version "8.3.6"
    id("org.graalvm.buildtools.native") version "0.10.4"
}

group = "dev.rambris"
version = "0.0.1-beta.8"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "dev.rambris.amigaamos.Main"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    implementation("info.picocli:picocli:4.7.6")
    annotationProcessor("info.picocli:picocli-codegen:4.7.6")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// ---------------------------------------------------------------------------
// Version code generation
// ---------------------------------------------------------------------------

val generateVersion by tasks.registering {
    val versionString = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/version/main/java")
    inputs.property("version", versionString)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.resolve("dev/rambris/amigaamos")
        dir.mkdirs()
        dir.resolve("Version.java").writeText(
            """
            /*
             * SPDX-FileCopyrightText: 2026 Fredrik Rambris <fredrik@rambris.com>
             * SPDX-License-Identifier: Apache-2.0
             * See LICENSE in the project root.
             */

            package dev.rambris.amigaamos;

            /** Generated by Gradle — do not edit. Version reflects {@code project.version} in build.gradle.kts. */
            public final class Version {
                public static final String VALUE = "$versionString";
                private Version() {}
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.main {
    java.srcDir(generateVersion.map { layout.buildDirectory.dir("generated/sources/version/main/java").get() })
}

tasks.test {
    useJUnitPlatform()
}

// ---------------------------------------------------------------------------
// picocli-codegen: emit GraalVM reflect-config.json at compile time
// ---------------------------------------------------------------------------

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-Aproject=${project.group}/${project.name}")
}

// ---------------------------------------------------------------------------
// GraalVM Native Image
// ---------------------------------------------------------------------------

graalvmNative {
    metadataRepository { enabled = true }   // pre-built configs for Jackson etc.
    binaries {
        named("main") {
            imageName = "portamos"
            buildArgs.addAll("--no-fallback", "-H:+ReportExceptionStackTraces")
            resources {
                // Embed all JSON definition files into the native binary.
                // getResourceAsStream("/amos/definitions/…") will work unchanged.
                includedPatterns.add("amos/definitions/.*\\.json")
            }
        }
    }
    toolchainDetection = false
}
