#!/usr/bin/env python3
"""Generate site/_data/changelog.yml from git tag messages.

Usage:
    python3 scripts/generate_changelog.py [--count N]

Reads the N most recent vX.Y.Z* tags (default 5), extracts their body
text, and writes site/_data/changelog.yml for Jekyll to consume.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

YAML_OUT = Path(__file__).parent.parent / "site" / "_data" / "changelog.yml"


def get_tags(count: int) -> list[str]:
    result = subprocess.run(
        ["git", "tag", "--sort=-version:refname", "-l", "v*beta.*"],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.splitlines()[:count]


def get_tag_body(tag: str) -> list[str]:
    result = subprocess.run(
        ["git", "tag", "-l", "--format=%(contents)", tag],
        capture_output=True, text=True, check=True,
    )
    lines = result.stdout.splitlines()
    # Skip first line (tag name or subject) and any leading blank lines
    body = []
    skip = True
    for line in lines:
        if skip:
            if line.strip() == "" or line.strip() == tag:
                continue
            skip = False
        body.append(line)
    # Remove trailing blank lines
    while body and not body[-1].strip():
        body.pop()
    return body


def parse_items(body: list[str]) -> list[str]:
    """Collapse wrapped bullet lines into single strings."""
    items = []
    current = None
    for line in body:
        if re.match(r"^[-*]\s+", line):
            if current is not None:
                items.append(current)
            current = re.sub(r"^[-*]\s+", "", line).strip()
        elif line.startswith("  ") and current is not None:
            # Continuation of previous bullet
            current += " " + line.strip()
        elif line.strip() == "":
            if current is not None:
                items.append(current)
                current = None
        else:
            # Non-bullet paragraph — treat as single item
            if current is not None:
                items.append(current)
            current = line.strip()
    if current is not None:
        items.append(current)
    return [i for i in items if i]


def yaml_str(s: str) -> str:
    """Emit a YAML double-quoted string, escaping backslashes and quotes."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=5)
    args = parser.parse_args()

    tags = get_tags(args.count)
    if not tags:
        print("No tags found.", file=sys.stderr)
        sys.exit(1)

    YAML_OUT.parent.mkdir(parents=True, exist_ok=True)

    with YAML_OUT.open("w") as f:
        f.write("# Auto-generated by scripts/generate_changelog.py — do not edit manually.\n")
        for tag in tags:
            body = get_tag_body(tag)
            items = parse_items(body)
            f.write(f"- tag: {yaml_str(tag)}\n")
            f.write(f"  changes:\n")
            if items:
                for item in items:
                    f.write(f"    - {yaml_str(item)}\n")
            else:
                f.write(f"    - {yaml_str('No release notes.')}\n")

    print(f"Written {YAML_OUT} ({len(tags)} releases)")


if __name__ == "__main__":
    main()
